I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/prolog.rpy", line 16, in script
    show laptop zoom 2 at charcenter  with fade
Exception: Image 'laptop' does not accept attributes 'zoom 2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/prolog.rpy", line 16, in script
    show laptop zoom 2 at charcenter  with fade
  File "/home/irina/UTM/SEM8/FDJ/renpy-8.2.0-sdk/renpy/ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/home/irina/UTM/SEM8/FDJ/renpy-8.2.0-sdk/renpy/ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "/home/irina/UTM/SEM8/FDJ/renpy-8.2.0-sdk/renpy/exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/home/irina/UTM/SEM8/FDJ/renpy-8.2.0-sdk/renpy/display/image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "/home/irina/UTM/SEM8/FDJ/renpy-8.2.0-sdk/renpy/display/displayable.py", line 246, in _duplicate
    args.extraneous()
  File "/home/irina/UTM/SEM8/FDJ/renpy-8.2.0-sdk/renpy/display/displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'laptop' does not accept attributes 'zoom 2'.

Linux-5.15.0-91-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.2.0.24012702
AcademicDishonesty 1.0
Sun Feb 25 20:16:07 2024
